version: '3'
services:
  mysql:
    restart: always
    image: mysql:5.7
    container_name: mysql
    volumes:
      - ./logs:/var/log/mysql
      - ./data:/var/lib/mysql
      - ./etc:/etc/mysql/conf.d
      #      数据库还原目录 可将需要还原的sql文件放在这里
      - ./source:/docker-entrypoint-initdb.d
    environment:
      - "MYSQL_ROOT_USERNAME=root"
      - "MYSQL_ROOT_PASSWORD=jq2m9x"
      - "TZ=Asia/Shanghai"
    ports:
      - 33061:3306
